version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
  web:
    image: golang:latest
    container_name: "my_go"
    working_dir: /go/src/app
    command: go run ./cmd/apiserver/main.go
    ports:
        - "8080:8080"
    volumes:
        - ./:/go/src/app
    links:
        - db
    environment:
      PORT: 8080

volumes:
  postgres-data: